version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: bin/stop.sh
      timeout: 120
      runas: ec2-user
  BeforeInstall:
    - location: bin/delete.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: bin/run.sh
      timeout: 120
      runas: ec2-user