version: 0.2

phases:
  install:
    commands:
      - echo installing NPM packages
      - npm install
artifacts:
  type: zip
  files:
    - appspec.yml
    - app.js
    - package.json
    - node_modules/**/*
    - bin/*